apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chat-bot.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "todo-chat-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
    {{- include "todo-chat-bot.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chat-bot.fullname" . }}-backend
  labels:
    app: backend
    {{- include "todo-chat-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend
    {{- include "todo-chat-bot.selectorLabels" . | nindent 4 }}